# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing_extensions import Literal, TypeAlias

__all__ = ["SecurityIDSource"]

SecurityIDSource: TypeAlias = Literal[
    "CMS",
    "CLST",
    "OPRA",
    "FIGI",
    "CUSIP",
    "CURRENCY",
    "FMP",
    "OEMS",
    "SEDOL",
    "QUIK",
    "ISIN",
    "RIC",
    "COUNTRY",
    "EXCHANGE",
    "CTA",
    "BLOOMBERG",
    "WERTPAPIER",
    "DUTCH",
    "VALOREN",
    "SICOVAM",
    "BELGIAN",
    "COMMON",
    "CLEARING_HOUSE",
    "ISDA_FPML_SPECIFICATION",
    "ISDA_FPML_URL",
    "LETTER_OF_CREDIT",
    "MARKETPLACE_ASSIGNED_IDENTIFIER",
    "MARKIT_RED_ENTITY_CLIP",
    "MARKIT_RED_PAIR_CLIP",
    "CFTC",
    "ISDA_COMMODITY_REFERENCE_PRICE",
    "LEGAL_ENTITY_IDENTIFIER",
    "SYNTHETIC",
    "FIDESSA_INSTRUMENT_MNEMONIC",
    "INDEX_NAME",
    "UNIFORM_SYMBOL",
    "DIGITAL_TOKEN_IDENTIFIER",
    "MASSIVE",
    "OTHER",
]
